name: "Test ocaml-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  init:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        ocaml-version: 4.08.1
    - run: opam depext -iyv yaml
