name: Builds, tests & co

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-12 # macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.0.x
        include:
          - os: windows-latest
            ocaml-compiler: 4.14.x
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.5.0.0+options,ocaml-option-32bit
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.5.0.0+options,ocaml-option-flambda,ocaml-option-musl,ocaml-option-static
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.5.2.0+trunk
            opam-repositories: |
              beta: https://github.com/ocaml/ocaml-beta-repository.git
              default: https://github.com/ocaml/opam-repository.git

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm packages
        if: runner.os == 'Linux'
        run: yarn install --immutable

      - name: Check formatting
        if: runner.os == 'Linux'
        run: yarn fmt:check

      - name: Check lint
        if: runner.os == 'Linux'
        run: yarn lint

      - name: Check type
        if: runner.os == 'Linux'
        run: yarn typecheck

      - name: Ensure dist directory is up-to-date
        if: runner.os == 'Linux'
        shell: bash
        run: |
          yarn build
          if [ "$(git status dist lint-doc lint-fmt lint-opam --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ./
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: ${{ matrix.opam-repositories }}

      - run: opam depext uri --install
