name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.14.x
        include:
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-32bit
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-flambda,ocaml-option-musl,ocaml-option-static
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.12.0+domains
            opam-repositories: |
              multicore: https://github.com/ocaml-multicore/multicore-opam.git
              default: https://github.com/ocaml/opam-repository.git

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm packages
        if: runner.os == 'Linux'
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        if: runner.os == 'Linux'
        run: pnpm fmt:check

      - name: Check lint
        if: runner.os == 'Linux'
        run: pnpm lint

      - name: Check type
        if: runner.os == 'Linux'
        run: pnpm typecheck

      - name: Ensure dist directory is up-to-date
        if: runner.os == 'Linux'
        shell: bash
        run: |
          pnpm build
          if [ "$(git status dist lint-doc lint-fmt lint-opam --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ./
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: ${{ matrix.opam-repositories }}

      - run: opam depext uri --install
